version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python get-by-id.py ${GMAPS_KEY}
            git add .
            git config --global user.email "updatebot@example.com"
            git config --global user.name "Updatebot"
            git commit -m "new ci update" && \
              git push -q https://${GH_TOKEN}@github.com/ryanvmenezes/la-populartimes-tracker.git master \
              || true

workflows:
  version: 2
  # build:
  #   jobs:
  #     - build-and-test
  hourly:
    triggers:
      - schedule:
          cron: "1 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
