version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python get-by-id.py
            git add .
            git config --global user.email "updatebot@example.com"
            git config --global user.name "Updatebot"
            git commit -m "new ci update" && \
              git push -q hhttps://${GITHUB_PERSONAL_TOKEN}@github.com/ryanvmenezes/la-populartimes-tracker.git circleci-project-setup \
              || true

workflows:
  main:
    jobs:
      - build-and-test
